import type React from "react"
import type { Metadata } from "next"
import { Work_Sans } from "next/font/google"
import "./globals.css"
import { Web3Provider } from "@/providers/Web3Provider"
import { AuthProvider } from "@/providers/AuthProvider"
import { Navbar } from "@/components/ui/navBar"
import { Footer } from "@/components/ui/footer"

const workSans = Work_Sans({ 
  subsets: ["latin"],
  weight: ['400', '700'],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "SpyAgents",
  description: "Generated by SpyAgents",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className="dark">
      <body className={`${workSans.variable} font-sans flex flex-col min-h-screen bg-background`}> 
        <Web3Provider>
          <AuthProvider>
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </AuthProvider>
        </Web3Provider>
      </body>
    </html>
  )
}
